image: alpine/edge
packages:
  - npm
  - rsync
secrets:
  - 3a8daec5-761a-4c5f-951f-f6463081dce2 # learningbay24 deploy
  - edda9cee-e1e4-4cd3-8096-7fc28363e0db # git.sr.ht-mirror
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no -i ~/.ssh/edda9cee-e1e4-4cd3-8096-7fc28363e0db
sources:
  - https://github.com/LearningBay24/LearningBay24-react
tasks:
  - setup: |
      cd LearningBay24-react/frontend/
      npm install
  - lint: |
      cd LearningBay24-react/frontend/
      npm install --save-dev eslint eslint-config-google
      npx eslint src/**/*.js
  - build: |
      cd LearningBay24-react/frontend/
      npm run build
  - nopr: |
      # Don't run on GitHub PRs
      [ "$BUILD_REASON" != 'github-pr' ] || complete-build
  - mirror: |
      cd LearningBay24-react
      git push -o skip-ci --force --mirror git@git.sr.ht:~witcher/LearningBay24-react
  - deploy: |
      if [ "$GITHUB_REF" != "refs/heads/main" ]
      then
        echo "Skipping deploying changes if not on main branch"
        exit
      fi
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      cd LearningBay24-react/frontend/
      rsync -r ./build/ srht-deploy@learningbay24.de:/var/www/learningbay24/html/
