image: alpine/edge
packages:
  - npm
  - rsync
sources:
  - https://github.com/LearningBay24/LearningBay24-react
secrets:
  - 3a8daec5-761a-4c5f-951f-f6463081dce2 # learningbay24 deploy
tasks:
  - build: |
      cd LearningBay24-react/frontend/
      npm install
      npm run build
  - deploy: |
      if [ "$GITHUB_REF" != "refs/heads/main" ]
      then
        echo "Skipping deploying changes if not on main branch"
        exit
      fi
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      cd LearningBay24-frontend/frontend/
      rsync -r ./build/ srht-deploy@learningbay24.de:/var/www/learningbay24/html/
