export const ActionTypes =
{
    FETCH_COURSES : "FETCH_COURSES",
    FETCH_COURSE : "FETCH_COURSE",
    SET_COURSE : "SET_COURSE",
    FETCH_USER : "FETCH_USER",
    SET_USER : "SET_USER",
    FETCH_EXAM : "FETCH_EXAM",
    SET_EXAM : "SET_EXAM",
    ERROR : "ERROR",
}
